/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import java.awt.BorderLayout;

/**
 *
 * @author jaant
 */
public class empresaPanel extends javax.swing.JPanel {

    /**
     * Creates new form empresaPanel
     */
    public empresaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncrearEmpresa = new javax.swing.JButton();
        btnmodificarEmpresa = new javax.swing.JButton();
        btneliminarEmpresa = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        txtEtiqueta = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1340, 590));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("SOLICITUD DE EMPRESA");

        btncrearEmpresa.setOpaque(false);
        btncrearEmpresa.setContentAreaFilled(false);
        btncrearEmpresa.setBorderPainted(false);
        //btncrearEmpresa.setBackground(Color.YELLOW);
        //btncrearEmpresa.setBackground(java.awt.Color.yellow);
        btncrearEmpresa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btncrearEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus (1).png"))); // NOI18N
        btncrearEmpresa.setText("  CREAR");
        btncrearEmpresa.setMaximumSize(new java.awt.Dimension(109, 25));
        btncrearEmpresa.setMinimumSize(new java.awt.Dimension(109, 25));
        btncrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearEmpresaActionPerformed(evt);
            }
        });

        btnmodificarEmpresa.setOpaque(false);
        btnmodificarEmpresa.setContentAreaFilled(false);
        btnmodificarEmpresa.setBorderPainted(false);
        btnmodificarEmpresa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnmodificarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update (1).png"))); // NOI18N
        btnmodificarEmpresa.setText(" MODIFICAR");
        btnmodificarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarEmpresaActionPerformed(evt);
            }
        });

        btneliminarEmpresa.setOpaque(false);
        btneliminarEmpresa.setContentAreaFilled(false);
        btneliminarEmpresa.setBorderPainted(false);
        btneliminarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x-button (1).png"))); // NOI18N
        btneliminarEmpresa.setText(" ELIMINAR");
        btneliminarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarEmpresaActionPerformed(evt);
            }
        });

        panelPrincipal.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        txtEtiqueta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEtiqueta.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncrearEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmodificarEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminarEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(txtEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtEtiqueta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btncrearEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodificarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btneliminarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearEmpresaActionPerformed
        // TODO add your handling code here:
        
        empresaCrear ec = new empresaCrear();
        ec.setSize(1050,500);
        ec.setLocation(5,5);
        txtEtiqueta.setText("CREAR EMPRESA");
        panelPrincipal.removeAll();
        panelPrincipal.add(ec,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();

    }//GEN-LAST:event_btncrearEmpresaActionPerformed

    private void btnmodificarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarEmpresaActionPerformed
        // TODO add your handling code here:
        empresaModificar em = new empresaModificar();
        em.setSize(1050,500);
        em.setLocation(5,5);
        txtEtiqueta.setText("MODIFICAR EMPRESA");
        panelPrincipal.removeAll();
        panelPrincipal.add(em,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnmodificarEmpresaActionPerformed

    private void btneliminarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarEmpresaActionPerformed
        // TODO add your handling code here:
        empresaEliminar ee = new empresaEliminar();
        ee.setSize(1050,500);
        ee.setLocation(5,5);
        txtEtiqueta.setText("ELIMINAR EMPRESA");
        panelPrincipal.removeAll();
        panelPrincipal.add(ee,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btneliminarEmpresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrearEmpresa;
    private javax.swing.JButton btneliminarEmpresa;
    private javax.swing.JButton btnmodificarEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel txtEtiqueta;
    // End of variables declaration//GEN-END:variables
}
