/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import clases.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jaant
 */
public class empresaEliminar extends javax.swing.JPanel {
conectar cc= new conectar();
    Connection cn = cc.conexion();
     String [] Datos = new String[8];
    /**
     * Creates new form empresaEliminar
     */
    public empresaEliminar() {
        initComponents();
        tblEmpresa.getColumnModel().getColumn(6).setMaxWidth(0);
        tblEmpresa.getColumnModel().getColumn(6).setMinWidth(0);
        tblEmpresa.getColumnModel().getColumn(6).setPreferredWidth(0);
        DefaultTableModel tabla = (DefaultTableModel)tblEmpresa.getModel();
        tabla.getDataVector().removeAllElements();
        revalidate();
        String sql="select * from empresa";
        try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Datos[0]=(String) rs.getObject(2);
                    Datos[1]=(String) rs.getObject(3);
                    Datos[2]=(String) rs.getObject(4);
                    Datos[3]=(String) rs.getObject(5);
                    Datos[4]=(String) rs.getObject(6);
                    Datos[5]=(String) rs.getObject(7);
                    Datos[6]=Integer.toString(rs.getInt(1));
                    
                    tabla.addRow(Datos);
                    tblEmpresa.setModel(tabla);
                }
            } catch (SQLException ex) {
                Logger.getLogger(empresaModificar.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnombreEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpresa = new javax.swing.JTable();

        setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de empresa");

        txtnombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreEmpresaKeyReleased(evt);
            }
        });

        tblEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre Empresa", "No de pasantes", "Descripción", "Nombre de contacto", "Número de contacto", "Correo de contacto", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEmpresa.setSelectionBackground(new java.awt.Color(144, 219, 90));
        tblEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(txtnombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreEmpresaKeyReleased
        // TODO add your handling code here:
 
        String aux;
        DefaultTableModel tabla = (DefaultTableModel)tblEmpresa.getModel();
        tabla.getDataVector().removeAllElements();
        revalidate();
        if (txtnombreEmpresa.getText()=="") {
            tabla.getDataVector().removeAllElements();
            revalidate();
            String sql="select * from empresa";
        }else{
            String sql="select * from empresa where nombre_empresa like'"+txtnombreEmpresa.getText()+"%'";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Datos[0]=(String) rs.getObject(2);
                    Datos[1]=(String) rs.getObject(3);
                    Datos[2]=(String) rs.getObject(4);
                    Datos[3]=(String) rs.getObject(5);
                    Datos[4]=(String) rs.getObject(6);
                    Datos[5]=(String) rs.getObject(7);
                    Datos[6]=Integer.toString(rs.getInt(1));
        
                    tabla.addRow(Datos);
                    tblEmpresa.setModel(tabla);
                }
            } catch (SQLException ex) {
                Logger.getLogger(empresaModificar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtnombreEmpresaKeyReleased

    private void tblEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpresaMouseClicked
        // TODO add your handling code here:
        int indice=tblEmpresa.getSelectedRow();
        int opcionEliminado;
        TableModel modelo = tblEmpresa.getModel();
        String id =modelo.getValueAt(indice,6).toString();
        String sql="DELETE FROM empresa WHERE (id_empresa = '"+id+"');";
        try {
            Statement st = (Statement)cn.createStatement();
            opcionEliminado=JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcionEliminado==0) {
                JOptionPane.showMessageDialog(null,"Eliminado");
                st.executeUpdate(sql);    
            }else{
                JOptionPane.showMessageDialog(null,"No Eliminado");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage() ,"Error", 1);
        }

    }//GEN-LAST:event_tblEmpresaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpresa;
    private javax.swing.JTextField txtnombreEmpresa;
    // End of variables declaration//GEN-END:variables
}
