/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasante;

import clases.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jaant
 */
public class pasanteModificar extends javax.swing.JPanel {
    conectar cc= new conectar();
    Connection cn = cc.conexion();
    String [] Datos = new String[10];
    /**
     * Creates new form pasanteModificar
     */
    public pasanteModificar() {
        initComponents();
        tblEstudiante.getColumnModel().getColumn(8).setMaxWidth(0);
        tblEstudiante.getColumnModel().getColumn(8).setMinWidth(0);
        tblEstudiante.getColumnModel().getColumn(8).setPreferredWidth(0);
        DefaultTableModel tabla = (DefaultTableModel)tblEstudiante.getModel();
        tabla.getDataVector().removeAllElements();
        revalidate();
        String sql="select * from alumno;";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Datos[0]=(String) rs.getObject(2);
                    Datos[1]=(String) rs.getObject(3);
                    Datos[2]=(String) rs.getObject(4);
                    Datos[3]=(String) rs.getObject(5);
                    Datos[4]=(String) rs.getObject(6);
                    Datos[5]=(String) rs.getObject(7);
                    Datos[6]=(String) rs.getObject(8);
                    Datos[7]=(String) rs.getObject(9);
                    
                    Datos[8]=Integer.toString(rs.getInt(1));
                    tabla.addRow(Datos);
                    tblEstudiante.setModel(tabla);
                }
            } catch (SQLException ex) {
                Logger.getLogger(pasanteModificar.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidEstudiante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiante = new javax.swing.JTable();

        setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Id de estudiante");

        txtidEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidEstudianteKeyReleased(evt);
            }
        });

        tblEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Alumno", "Cédula Alumno", "Nombre Alumno", "Apellido Alumno", "Nivel Alumno", "Carrera Alumno", "Periódo Académico", "Teléfono Alumno", "cod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEstudiante.setSelectionBackground(new java.awt.Color(144, 219, 90));
        tblEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudianteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstudiante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(txtidEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidEstudianteKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tabla = (DefaultTableModel)tblEstudiante.getModel();
        tabla.getDataVector().removeAllElements();
        revalidate();
        if (txtidEstudiante.getText()=="") {
            tabla.getDataVector().removeAllElements();
            revalidate();
            String sql="select * from alumno";
        }else{
            String sql="select * from alumno where id_alum_universidad like'"+txtidEstudiante.getText()+"%'";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while(rs.next()){
                    Datos[0]=(String) rs.getObject(2);
                    Datos[1]=(String) rs.getObject(3);
                    Datos[2]=(String) rs.getObject(4);
                    Datos[3]=(String) rs.getObject(5);
                    Datos[4]=(String) rs.getObject(6);
                    Datos[5]=(String) rs.getObject(7);
                    Datos[6]=(String) rs.getObject(8);
                    Datos[7]=(String) rs.getObject(9);
                    Datos[8]=(String) rs.getObject(10);
                    Datos[9]=Integer.toString(rs.getInt(1));
                    tabla.addRow(Datos);
                    tblEstudiante.setModel(tabla);
                }
            } catch (SQLException ex) {
                Logger.getLogger(pasanteModificar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtidEstudianteKeyReleased

    private void tblEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudianteMouseClicked
        // TODO add your handling code here:
        
        int indice=tblEstudiante.getSelectedRow();
        TableModel modelo = tblEstudiante.getModel();
        String id = modelo.getValueAt(indice,8).toString();
        alumnomodificartabla ventana = new alumnomodificartabla(id);
        ventana.setVisible(true);

    }//GEN-LAST:event_tblEstudianteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstudiante;
    private javax.swing.JTextField txtidEstudiante;
    // End of variables declaration//GEN-END:variables
}
