/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasante;

import java.awt.BorderLayout;

/**
 *
 * @author jaant
 */
public class pasantepanel extends javax.swing.JPanel {

    /**
     * Creates new form pasantepanel
     */
    public pasantepanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btneliminarAlumno = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btncrearAlumno = new javax.swing.JButton();
        btnmodificarAlumno = new javax.swing.JButton();
        txtEtiqueta = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        btneliminarAlumno.setOpaque(false);
        btneliminarAlumno.setContentAreaFilled(false);
        btneliminarAlumno.setBorderPainted(false);
        btneliminarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x-button (1).png"))); // NOI18N
        btneliminarAlumno.setText(" ELIMINAR");
        btneliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarAlumnoActionPerformed(evt);
            }
        });

        panelPrincipal.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALUMNOS");

        btncrearAlumno.setOpaque(false);
        btncrearAlumno.setContentAreaFilled(false);
        btncrearAlumno.setBorderPainted(false);
        //btncrearEmpresa.setBackground(Color.YELLOW);
        //btncrearEmpresa.setBackground(java.awt.Color.yellow);
        btncrearAlumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btncrearAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus (1).png"))); // NOI18N
        btncrearAlumno.setText("  CREAR");
        btncrearAlumno.setMaximumSize(new java.awt.Dimension(109, 25));
        btncrearAlumno.setMinimumSize(new java.awt.Dimension(109, 25));
        btncrearAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearAlumnoActionPerformed(evt);
            }
        });

        btnmodificarAlumno.setOpaque(false);
        btnmodificarAlumno.setContentAreaFilled(false);
        btnmodificarAlumno.setBorderPainted(false);
        btnmodificarAlumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnmodificarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update (1).png"))); // NOI18N
        btnmodificarAlumno.setText(" MODIFICAR");
        btnmodificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarAlumnoActionPerformed(evt);
            }
        });

        txtEtiqueta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(txtEtiqueta))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btncrearAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmodificarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1105, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(232, 232, 232)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtEtiqueta))
                .addGap(18, 18, 18)
                .addComponent(btncrearAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnmodificarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btneliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarAlumnoActionPerformed
        // TODO add your handling code here:
        pasanteEliminar pe = new pasanteEliminar();
        pe.setSize(1050,500);
        pe.setLocation(5,5);
        txtEtiqueta.setText("ELIMINAR ALUMNO");
        panelPrincipal.removeAll();
        panelPrincipal.add(pe,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btneliminarAlumnoActionPerformed

    private void btncrearAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearAlumnoActionPerformed
        // TODO add your handling code here:

        pasanteCrear pc = new pasanteCrear();
        pc.setSize(1050,500);
        pc.setLocation(5,5);
        txtEtiqueta.setText("REGISTRAR ALUMNO");
        panelPrincipal.removeAll();
        panelPrincipal.add(pc,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btncrearAlumnoActionPerformed

    private void btnmodificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarAlumnoActionPerformed
        // TODO add your handling code here:
        pasanteModificar pm = new pasanteModificar();
        pm.setSize(1050,500);
        pm.setLocation(5,5);
        txtEtiqueta.setText("MODIFICAR ALUMNO");
        panelPrincipal.removeAll();
        panelPrincipal.add(pm,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnmodificarAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrearAlumno;
    private javax.swing.JButton btneliminarAlumno;
    private javax.swing.JButton btnmodificarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel txtEtiqueta;
    // End of variables declaration//GEN-END:variables
}
